[package]
name = "perpetuals"
version = "0.1.0"
description = "Solana Perpetuals Exchange"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/perpetuals"
categories = ["finance"]
keywords = ["solana", "dex", "perpetuals", "futures", "exchange"]
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "perpetuals"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = []
test = []
devnet = []
default = ["cpi", "devnet"]

[dependencies]
anchor-lang = {version = "0.28.0", features = ["init-if-needed"]}
anchor-spl = "0.28.0"
solana-program = "1.16.16"
solana-security-txt = "1.1.1"
pyth-sdk-solana = "0.8.0"
num-traits = "0.2.15"
num = "0.4.0"
bytemuck = "1.13.1"
ahash = "=0.7.7"

# 2af3b6e4d15dd3f006e8a292436ed095a46ceae5
spl-governance = { rev = "2af3b6e", git = "https://github.com/solana-labs/solana-program-library", features = ["no-entrypoint"] }

# clockwork-sdk = { version = "=2.0.17" }
clockwork-sdk = { git = "https://github.com/AdrenaDEX/clockwork.git", branch = "anchor-0.28.0" }

[dev-dependencies]
solana-program-test = "1.16.16"
solana-sdk = "1.16.16"
tokio = { version = "1.0.0", features = ["macros"]}
bonfida-test-utils = "0.2.1"
bincode = "1.3.3"
proptest = "1.1.0"
clockwork-thread-program = { git = "https://github.com/AdrenaDEX/clockwork.git", branch = "anchor-0.28.0" }
clockwork-network-program = { git = "https://github.com/AdrenaDEX/clockwork.git", branch = "anchor-0.28.0" }
maplit = "1.0.2"