[features]
seeds = false
[programs.localnet]
perpetuals = "8G3kMWNnogX2jTYu3Yrq7vz1UdhMYQDPeCDpHZZzkfCL"
[programs.devnet]
perpetuals = "8G3kMWNnogX2jTYu3Yrq7vz1UdhMYQDPeCDpHZZzkfCL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
